import React, { useState } from 'react';
import { Sparkles, Save, RotateCcw, Copy, Trash2 } from 'lucide-react';
import toast from 'react-hot-toast';
import * as newsroomService from '../services/newsroomService';

const AIEditor = () => {
  const [topic, setTopic] = useState('');
  const [title, setTitle] = useState('');
  const [content, setContent] = useState('');
  const [summary, setSummary] = useState('');
  const [category, setCategory] = useState('');
  const [loading, setLoading] = useState(false);
  const [saving, setSaving] = useState(false);
  const [history, setHistory] = useState([]);

  const saveToHistory = () => {
    if (content.trim()) {
      setHistory([
        ...history,
        {
          id: Date.now(),
          title,
          content,
          summary,
          category,
          timestamp: new Date().toLocaleTimeString()
        }
      ]);
      toast.success('Snapshot saved to history');
    }
  };

  const restoreFromHistory = (snapshot) => {
    setTitle(snapshot.title);
    setContent(snapshot.content);
    setSummary(snapshot.summary);
    setCategory(snapshot.category);
    toast.success('Restored from history');
  };

  const handleSaveArticle = async () => {
    if (!title.trim() || !content.trim()) {
      toast.error('Title and content are required');
      return;
    }

    setSaving(true);
    try {
      await newsroomService.createArticle({
        title: title.trim(),
        content: content.trim(),
        summary: summary.trim(),
        category: category.trim(),
        status: 'draft'
      });
      toast.success('Article saved to drafts');
      resetForm();
    } catch (error) {
      toast.error('Failed to save: ' + error.message);
    } finally {
      setSaving(false);
    }
  };

  const resetForm = () => {
    setTopic('');
    setTitle('');
    setContent('');
    setSummary('');
    setCategory('');
  };

  const copyToClipboard = (text) => {
    navigator.clipboard.writeText(text);
    toast.success('Copied to clipboard!');
  };

  const handleGenerateArticle = () => {
    // Placeholder for AI generation - in a real scenario this would call an AI API
    if (!topic.trim()) {
      toast.error('Enter a topic first');
      return;
    }

    setLoading(true);
    // Simulate AI processing
    setTimeout(() => {
      setTitle(`Breaking News: ${topic}`);
      setContent(`This is a sample article about ${topic}. In a production environment, this would be generated by your AI system. Replace this with actual AI API calls to your language model.`);
      setSummary(`Summary about ${topic}`);
      setCategory('News');
      setLoading(false);
      toast.success('Article template generated!');
    }, 2000);
  };

  return (
    <div className="bg-slate-50 dark:bg-slate-950 min-h-screen p-6 md:p-8">
      {/* Header */}
      <div className="mb-8">
        <h1 className="text-3xl md:text-4xl font-semibold tracking-tight text-slate-900 dark:text-slate-100 mb-2">
          AI Article Editor
        </h1>
        <p className="text-slate-600 dark:text-slate-400">
          Create, edit, and optimize articles with AI assistance
        </p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Main Editor */}
        <div className="lg:col-span-2 space-y-6">
          {/* Topic Input */}
          <div className="bg-white dark:bg-slate-900 rounded-xl shadow-sm p-6 border border-slate-200 dark:border-slate-800">
            <label className="block text-sm font-medium text-slate-700 dark:text-slate-300 mb-2">
              Topic or Prompt
            </label>
            <input
              type="text"
              value={topic}
              onChange={(e) => setTopic(e.target.value)}
              placeholder="Enter a topic to generate an article..."
              className="w-full px-4 py-3 border border-slate-300 dark:border-slate-700 bg-white dark:bg-slate-950 text-slate-900 dark:text-slate-100 rounded-md focus:ring-2 focus:ring-slate-400/40 placeholder-slate-400 dark:placeholder-slate-500"
            />
            <button
              onClick={handleGenerateArticle}
              disabled={loading || !topic.trim()}
              className="mt-3 w-full flex items-center gap-2 justify-center px-6 py-3 bg-slate-900 dark:bg-slate-100 hover:bg-slate-800 dark:hover:bg-slate-200 disabled:opacity-50 disabled:cursor-not-allowed text-slate-100 dark:text-slate-900 rounded-md font-medium transition-colors"
            >
              {loading ? (
                <>
                  <div className="animate-spin">
                    <Sparkles size={20} />
                  </div>
                  Generating...
                </>
              ) : (
                <>
                  <Sparkles size={20} />
                  Generate Draft
                </>
              )}
            </button>
          </div>

          {/* Title */}
          <div className="bg-white dark:bg-slate-900 rounded-xl shadow-sm p-6 border border-slate-200 dark:border-slate-800">
            <label className="block text-sm font-medium text-slate-700 dark:text-slate-300 mb-2">
              Title
            </label>
            <input
              type="text"
              value={title}
              onChange={(e) => setTitle(e.target.value)}
              placeholder="Article title"
              className="w-full px-4 py-3 border border-slate-300 dark:border-slate-700 bg-white dark:bg-slate-950 text-slate-900 dark:text-slate-100 rounded-md focus:ring-2 focus:ring-slate-400/40"
            />
          </div>

          {/* Content */}
          <div className="bg-white dark:bg-slate-900 rounded-xl shadow-sm p-6 border border-slate-200 dark:border-slate-800">
            <div className="flex items-center justify-between mb-2">
              <label className="block text-sm font-medium text-slate-700 dark:text-slate-300">
                Content
              </label>
              <button
                onClick={() => copyToClipboard(content)}
                className="p-1 hover:bg-slate-200 dark:hover:bg-slate-800 rounded transition-colors"
                title="Copy to clipboard"
              >
                <Copy size={16} className="text-slate-600 dark:text-slate-400" />
              </button>
            </div>
            <textarea
              value={content}
              onChange={(e) => setContent(e.target.value)}
              placeholder="Article content..."
              rows={12}
              className="w-full px-4 py-3 border border-slate-300 dark:border-slate-700 bg-white dark:bg-slate-950 text-slate-900 dark:text-slate-100 rounded-md focus:ring-2 focus:ring-slate-400/40 resize-none"
            />
            <p className="text-xs text-slate-500 dark:text-slate-400 mt-2">
              {content.length} characters | {content.split(/\s+/).length} words
            </p>
          </div>

          {/* Summary */}
          <div className="bg-white dark:bg-slate-900 rounded-xl shadow-sm p-6 border border-slate-200 dark:border-slate-800">
            <label className="block text-sm font-medium text-slate-700 dark:text-slate-300 mb-2">
              Summary
            </label>
            <textarea
              value={summary}
              onChange={(e) => setSummary(e.target.value)}
              placeholder="Brief summary..."
              rows={4}
              className="w-full px-4 py-3 border border-slate-300 dark:border-slate-700 bg-white dark:bg-slate-950 text-slate-900 dark:text-slate-100 rounded-md focus:ring-2 focus:ring-slate-400/40 resize-none"
            />
          </div>

          {/* Category */}
          <div className="bg-white dark:bg-slate-900 rounded-xl shadow-sm p-6 border border-slate-200 dark:border-slate-800">
            <label className="block text-sm font-medium text-slate-700 dark:text-slate-300 mb-2">
              Category
            </label>
            <input
              type="text"
              value={category}
              onChange={(e) => setCategory(e.target.value)}
              placeholder="e.g., Technology, Politics, Sports..."
              className="w-full px-4 py-3 border border-slate-300 dark:border-slate-700 bg-white dark:bg-slate-950 text-slate-900 dark:text-slate-100 rounded-md focus:ring-2 focus:ring-slate-400/40"
            />
          </div>

          {/* Actions */}
          <div className="flex gap-3">
            <button
              onClick={handleSaveArticle}
              disabled={saving || !title.trim() || !content.trim()}
              className="flex-1 flex items-center gap-2 justify-center px-6 py-3 bg-emerald-700 hover:bg-emerald-800 disabled:opacity-50 disabled:cursor-not-allowed text-white rounded-md font-medium transition-colors"
            >
              <Save size={20} />
              Save as Draft
            </button>
            <button
              onClick={saveToHistory}
              disabled={!content.trim()}
              className="flex-1 flex items-center gap-2 justify-center px-6 py-3 bg-indigo-700 hover:bg-indigo-800 disabled:opacity-50 disabled:cursor-not-allowed text-white rounded-md font-medium transition-colors"
            >
              <RotateCcw size={20} />
              Save Snapshot
            </button>
            <button
              onClick={resetForm}
              className="flex items-center gap-2 justify-center px-6 py-3 bg-slate-300 hover:bg-slate-400 dark:bg-slate-800 dark:hover:bg-slate-700 text-slate-900 dark:text-slate-100 rounded-md font-medium transition-colors"
            >
              <Trash2 size={20} />
              Clear
            </button>
          </div>
        </div>

        {/* Sidebar - History & Quick Actions */}
        <div className="space-y-6">
          {/* History */}
          {history.length > 0 && (
            <div className="bg-white dark:bg-slate-900 rounded-xl shadow-sm p-6 border border-slate-200 dark:border-slate-800">
              <h3 className="text-lg font-semibold text-slate-900 dark:text-slate-100 mb-4">
                Edit History
              </h3>
              <div className="space-y-2 max-h-96 overflow-y-auto">
                {history.map((snapshot, idx) => (
                  <div key={snapshot.id} className="p-3 bg-slate-50 dark:bg-slate-800 rounded-md border border-slate-200 dark:border-slate-700 cursor-pointer hover:bg-slate-100 dark:hover:bg-slate-700 transition-colors">
                    <p className="text-sm font-medium text-slate-900 dark:text-slate-100 truncate mb-1">
                      {snapshot.title || `Snapshot ${idx + 1}`}
                    </p>
                    <p className="text-xs text-slate-500 dark:text-slate-400 mb-2">{snapshot.timestamp}</p>
                    <button
                      onClick={() => restoreFromHistory(snapshot)}
                      className="text-xs px-2 py-1 bg-slate-900 dark:bg-slate-100 hover:bg-slate-800 dark:hover:bg-slate-200 text-slate-100 dark:text-slate-900 rounded transition-colors"
                    >
                      Restore
                    </button>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Tips */}
          <div className="bg-white dark:bg-slate-900 rounded-xl p-6 border border-slate-200 dark:border-slate-800">
            <h3 className="font-semibold text-slate-900 dark:text-slate-100 mb-3">Editor Notes</h3>
            <ul className="text-sm text-slate-700 dark:text-slate-300 space-y-2">
              <li>Save snapshots before major rewrites.</li>
              <li>Use generated drafts as a starting point, not final copy.</li>
              <li>Review tone, facts, and structure before publishing.</li>
              <li>Use clear categories for better content organization.</li>
            </ul>
          </div>

          {/* Character Limits */}
          <div className="bg-white dark:bg-slate-900 rounded-xl shadow-sm p-6 border border-slate-200 dark:border-slate-800">
            <h3 className="font-semibold text-slate-900 dark:text-slate-100 mb-4">Content Stats</h3>
            <div className="space-y-3">
              <div>
                <div className="flex justify-between text-sm mb-1">
                  <span className="text-slate-600 dark:text-slate-400">Title</span>
                  <span className="font-semibold text-slate-900 dark:text-slate-100">{title.length}</span>
                </div>
                <div className="w-full bg-slate-200 dark:bg-slate-800 rounded-full h-2">
                  <div className="bg-slate-500 h-2 rounded-full" style={{ width: `${Math.min(100, (title.length / 60) * 100)}%` }}></div>
                </div>
              </div>
              <div>
                <div className="flex justify-between text-sm mb-1">
                  <span className="text-slate-600 dark:text-slate-400">Content</span>
                  <span className="font-semibold text-slate-900 dark:text-slate-100">{content.split(/\s+/).length} words</span>
                </div>
                <div className="w-full bg-slate-200 dark:bg-slate-800 rounded-full h-2">
                  <div className="bg-indigo-500 h-2 rounded-full" style={{ width: `${Math.min(100, (content.split(/\s+/).length / 500) * 100)}%` }}></div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default AIEditor;
